name: Release Notebook Package
on:
  push:
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
  pypa:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv package
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies with pipenv
        run: |
          pipenv install --dev --system --ignore-pipfile --deploy
      - name: Build Pypi Dist
        run: |
          make dist
      - name: Publish Pypi Package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
